- app/jobs/developer/onboarding/slack_job.rb
Previously we received `superclass mismatch for class Onboarding` error
on heroku.
Most probably it happened because jobs, namespaced under `Onboarding`
have been loaded before actual `Developer::Onboarding` class.
This commit should fix that.
> Fix production crash

- app/cells/developer/dashboard/test_task_status_button.rb
- app/cells/developer/dashboard/test_task_status_button/show.haml
- app/controllers/web/dashboard/test_tasks_controller.rb
- app/models/developer/test_task.rb
- app/models/role.rb
- app/operations/ops/developer/screening/start.rb
- app/policies/test_task_policy.rb
- app/views/web/dashboard/test_tasks/index.html.haml
- config/locales/dashboard/en.yml
- config/routes.rb
- db/migrate/20180606070102_add_state_column_to_test_tasks.rb
- db/schema.rb
- spec/cells/developer/dashboard/test_task_status_button_spec.rb
- spec/controllers/web/dashboard/test_task_controller_spec.rb
- spec/factories/developer_test_tasks.rb
- spec/factories/roles.rb
- spec/operations/ops/developer/screening/start_spec.rb
- spec/policies/test_task_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/137
Убрал возможность удалять test task, добвил действия на активацию и отключение test tasks.
> (#137) add state to test task, activate/deactivate actions

- app/cells/developer/dashboard/onboarding_step_status.rb
- app/cells/developer/dashboard/user_status_button.rb
- app/views/web/dashboard/users/show.html.haml
- spec/cells/developer/dashboard/onboarding_step_status_spec.rb
- spec/cells/developer/dashboard/user_status_button_spec.rb
https://github.com/howtohireme/give-me-poc/issues/170
Убрал активность кнопок, где нет необходимость вызывать метод активации пользователя.
- [] RSpec tests are passing on CI
- [] Cucumber features are passing localy
- [+] `bin/cop -a` does not return any warnings
- [+] Tested manually
> (#170) fix link to actvate users in user management

- app/controllers/web/dashboard/test_task_assignments_controller.rb
- app/mailers/staff/screening_completed_mailer.rb
- app/policies/test_task_assignment_policy.rb
- app/queries/reviewable_applicants_query.rb
- app/queries/users/screening_completed_notification_recipients_query.rb
- spec/controllers/web/dashboard/test_task_assignments_controller_spec.rb
- spec/factories/skills.rb
- spec/factories/users.rb
- spec/mailers/staff/screening_completed_mailer_spec.rb
- spec/policies/test_task_assignment_policy_spec.rb
- spec/queries/reviewable_applicants_query_spec.rb
- spec/queries/users/screening_completed_notification_recipients_query_spec.rb
- spec/spec_helper.rb
Issue #158 
We should permit mentors to approve only those applicants, who have the same primary skill.
Otherwise, the mentor is not qualified enough to make such decisions.
Add yourself a role as a mentor.
Create several applicants, and some of them with different primary skill
Make sure that all steps a checked before a merge
> Mentor reviews applications

- lib/sidekiq_constraint.rb
- spec/lib/sidekiq_constraint_spec.rb
https://github.com/howtohireme/give-me-poc/issues/162
fix bug, when sorcery does not sign out after destroy user, when get sidekiq
* create new staff user
* www.lvh.me:3000/sidekiq
* open rails console and destroy staff user
* visit www.lvh.me:3000/sidekiq
> (#162) fix bug, when sorcery does not sign out after destroy user

- app/controllers/web/dashboard/test_tasks_controller.rb
- app/models/developer/test_task.rb
- app/models/skill.rb
- app/operations/ops/developer/screening/start.rb
- app/views/web/dashboard/test_tasks/_form.html.haml
- app/views/web/dashboard/test_tasks/index.html.haml
- config/locales/dashboard/en.yml
- db/migrate/20180613051425_add_reference_skill_to_test_task.rb
- db/migrate/20180613051541_add_skill_id.rb
- db/migrate/20180613051648_add_index_test_task.rb
- db/migrate/20180613051825_skill_to_ruby.rb
- db/migrate/20180613060946_change_users_primary_skill.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/web/dashboard/test_task_controller_spec.rb
- spec/controllers/web/dashboard/test_tasks_controller_spec.rb
- spec/factories/developer_test_tasks.rb
- spec/factories/roles.rb
- spec/models/developer/test_task_spec.rb
- spec/operations/ops/developer/screening/start_spec.rb
Issue #157 #.
Create belongs_to Skill relation at TestTask. Create a data migration that will update all existing test tasks to be related to Ruby skill. Add select to choose test task skill at edit form. On screening start operation select only those test tasks, that are related to user's primary skill.
Мне помощь с тестами нужна. Запутался во многообразии фабрик и их связей между друг-другом.  Skill не получается как-то безболезненно прикрутить, именно из-за тестов (start_spec.rb). Вручную протестировал - работает нормально.
> 157 belong_to Skill relation for task

- spec/controllers/web/dashboard/test_task_assignments_controller_spec.rb
- spec/factories/developer_test_tasks.rb
- spec/operations/ops/developer/screening/start_spec.rb
Issue #213 
Fix flaky factory, which caused random spec failures
- (n/a) Cucumber features are passing localy
> Fix flaky test_task factory

- app/controllers/web/dashboard/test_task_assignments_controller.rb
- app/controllers/web/dashboard/users_controller.rb
- app/models/user.rb
- app/operations/ops/developer/activate.rb
- app/views/web/dashboard/users/index.html.haml
- app/views/web/dashboard/users/show.html.haml
- config/locales/dashboard/en.yml
- db/migrate/20180615142120_add_approver_column_to_users.rb
- db/schema.rb
- spec/controllers/web/dashboard/test_task_assignments_controller_spec.rb
- spec/controllers/web/dashboard/users_controller_spec.rb
- spec/models/user_spec.rb
- spec/operations/ops/developer/activate_spec.rb
https://github.com/howtohireme/give-me-poc/issues/188
Add approver_id column to users.
Also add relation between user and approved user.
When we call Approve operation, add current_user as approver to applicant.
And in user management show action display who has approved user.
* gup
* rails db:migrate
* Click button to activate user in User management
* View information about the approving user in the approval line (action show User controller)
> (#188) add information about approver user to user model

- app/cells/developer/dashboard/user_roles.rb
- app/cells/developer/dashboard/user_roles/show.haml
- app/policies/user_policy.rb
- spec/cells/developer/dashboard/user_roles_spec.rb
- spec/policies/user_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/163
do not display manage roles to mentor
* Login staff user
* Go to http://dashboard.lvh.me:3000/users/#{id}
* View in row Roles - links to assign/unassign roles
* Go to show current user http://dashboard.lvh.me:3000/users/current_user.id
* Add role mentor and remove role staff
* The edit button and the link to managing the roles should disappear and only the current roles in the form of text remain
Current user staff
Current user mentor, not staff
Current user only role developer:
> (#163) do not display manage roles to mentor

- Gemfile
- Gemfile.lock
- app/cells/developer/dashboard/user_status_button.rb
- app/controllers/web/dashboard/test_task_assignments_controller.rb
- app/policies/dashboard/idea_policy.rb
- app/policies/dashboard/skill_policy.rb
- app/policies/dashboard_policy.rb
- app/policies/test_task_assignment_policy.rb
- app/policies/test_task_policy.rb
- app/policies/user_policy.rb
- app/views/web/dashboard/users/index.html.haml
- spec/cells/developer/dashboard/user_status_button_spec.rb
- spec/factories/users.rb
- spec/policies/test_task_assignment_policy_spec.rb
- spec/policies/web/dashboard/idea_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/318
Update pundit to 2.0.0.beta
Fix rights to activate candidates
* Current user has role staff
* in user management sees a button Review applicant in the candidate with the status screening completed
* in Applicants can only activate users with the status screening completed
* Current user has role mentor
* in user management sees a button Review applicant in the candidate with the status screening completed if primary skill equal.
* in Applicants can only activate users with the status screening completed and equal primary skill
https://github.com/howtohireme/give-me-poc-features/pull/19
> 318 bug activate users

- db/migrate/20180804140335_remove_skill_id_from_users.rb
- db/schema.rb
Issue #343 
Remove unused column
> Remove Users#skill_id column

- app/jobs/projects/create_slack_channel_job.rb
- app/operations/ops/projects/generate_project_slack_channel.rb
- app/operations/ops/projects/kickoff.rb
- app/services/slack_service.rb
- spec/jobs/projects/create_slack_channel_job_spec.rb
- spec/operations/ops/projects/generate_project_slack_channel_spec.rb
- spec/operations/ops/projects/kickoff_spec.rb
- spec/services/slack_service_spec.rb
https://github.com/howtohireme/give-me-poc/issues/13
(#13) generate slack channel for project
> (#13) generate slack channel for project

- app/mailers/staff/screening_completed_mailer.rb
- app/views/mailers/staff/screening_completed_mailer/notify.html.haml
- spec/mailers/staff/screening_completed_mailer_spec.rb
Issue #373 
User Github as a link in an email completed
> Profile github as link when email completed 

- app/models/concerns/rolable.rb
- db/data/20180819123314_migrate_applicants_state.rb
- db/data_schema.rb
- spec/models/user_spec.rb
Issue #371 
Update certain developer role states to be consistent with new states schema
> Mark roles with `profile_completed` as `policy_accepted`

- .travis.yml
- bin/test-migrations
Issue #210 
Ensure that migrations do not fail on production db
> Test migrations on travis

- config/initializers/sorcery.rb
- config/settings.yml
- config/settings/test.yml
- spec/controllers/web/bootcamp/oauths_controller_spec.rb
Issue #323 
Remove explicit dependency on ENV at spec
> Get rid of explicit ENV dependency in specs

- app/operations/ops/member/screening/message_to_slack.rb
- spec/operations/ops/member/screening/message_to_slack_spec.rb
Issue #492 
This PR addresses the typo in the notification of a new member screening being completed. *Completed* was misspelled as **comleted**.
* Complete a new member screening
* View slack notification that had previously shown the incorrect spelling of _completed_, is now spelled correctly.
* Profit 💸
> fix: 'comleted' -> 'completed'

- db/migrate/20181106174224_add_onboarding_complete_date_at_to_member_onboardins.rb
- db/schema.rb
- spec/factories/member_onboardings.rb
- spec/operations/ops/member/onboarding_spec.rb
Issue #520 
Sets onboarding complete date
1. Join give-me-poc as specialist
2. Force created user activation via admin panel
3. Via pgAdmin (or other tool) check member_onboardings table for a new records
4. _onboarding_complete_date_at_ must containt current date
> 520 onboarding complete date

- app/controllers/web/dashboard/notes_controller.rb
- app/helpers/subdomain_url_helper.rb
- app/views/layouts/dashboard.html.haml
- app/views/layouts/shared/_navigation.html.haml
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/sorcery.rb
- config/routes.rb
- config/settings/test.yml
- spec/cells/web/bootcamp/join_button_spec.rb
- spec/controllers/web/bootcamp/oauths_controller_spec.rb
- spec/helpers/subdomain_url_helper_spec.rb
Issue #479 
We get rid of multiple subdomains for simplicity. It will allow us to setup analytics for the website and prevent having issues with session across multiple domains.
[PR #32](https://github.com/howtohireme/give-me-poc-features/pull/32)
> Get rid of multiple domains

- app/controllers/web/bootcamp/wizard/profiles_controller.rb
- app/controllers/web/dashboard/profiles_controller.rb
- app/controllers/web/idea/wizard/registrations_controller.rb
- app/forms/base_user_form.rb
- app/models/user.rb
- app/views/web/bootcamp/wizard/profiles/edit.html.haml
- app/views/web/dashboard/profiles/edit.html.haml
- app/views/web/dashboard/profiles/show.html.haml
- app/views/web/idea/wizard/registrations/new.html.haml
- config/locales/dashboard/en.yml
- config/locales/dashboard/ru.yml
- config/locales/simple_form.en.yml
- config/locales/simple_form.ru.yml
- db/migrate/20181224215628_add_about_to_users.rb
- db/schema.rb
- spec/controllers/web/dashboard/profiles_controller_spec.rb
- spec/controllers/web/idea/wizard/registrations_controller_spec.rb
- spec/factories/users.rb
- spec/forms/author/registration_form_spec.rb
- spec/forms/member/profile_form_spec.rb
- spec/forms/member/update_user_form_spec.rb
- spec/forms/member/wizard/profile_form_spec.rb
- spec/operations/ops/author/sign_up_spec.rb
- spec/operations/ops/member/complete_profile_spec.rb
Issue #448
Add about field to user model
* Step 1
* Step 2
* Step 3
> 448 Add about field to user profile

- README.md
Update the link from symbiod.org to www.symbiod.org because symbiod.org don't redirect to the project
> Update link from symbiod.org to www.symbiod.org
