.rubocop.yml, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb, config/locales/simple_form.en.yml, lib/templates/haml/scaffold/_form.html.haml
generate config simple-form
https://github.com/howtohireme/give-me-poc/issues/49
=> (#49) genarate simple_form config

spec/controllers/web/dashboard/test_task_assignments_controller_spec.rb
https://github.com/howtohireme/give-me-poc/issues/50
Добавил 3 теста, для проверки можно запустить:
rspec spec/controllers/web/dashboard/test_task_assignments_controller_spec.rb
=> (#50) write 3 pending spec to test_task_assignments_controller_spec.rb

app/views/layouts/dashboard.html.haml, app/views/layouts/shared/_dashboard_flashes.html.haml
https://github.com/howtohireme/give-me-poc/issues/65
create partial flash, add code to dashboard layout.
Add testing code to controller home_dashboard
=> (#65) add flash partial to layout dashboard

app/views/layouts/dashboard.html.haml
https://github.com/howtohireme/give-me-poc/issues/75
Обновил ссылку в шаблоне app/views/layouts/dashboard.html.haml на js bootstrap, удалил из шаблона popper.min.js, теперь ошибок в логах нету.
=> (#75) update layout dashboard

config/initializers/sorcery.rb
https://github.com/howtohireme/give-me-poc/issues/56
Добавил запись логина пользователя и url профиля github при создании пользователя.
=> (#56) add user login and github to create user

app/controllers/web/dashboard/base_controller.rb, app/controllers/web/dashboard/users_controller.rb, app/errors/custom_errors.rb, app/models/role.rb, app/models/user.rb, app/operations/ops/developer/activate.rb, app/operations/ops/developer/add_role.rb, app/operations/ops/developer/assign_role.rb, app/operations/ops/developer/disable.rb, app/operations/ops/developer/remove_role.rb, app/operations/ops/developer/unassign_role/last_role_error.rb, app/policies/user_policy.rb, app/views/layouts/dashboard.html.haml, app/views/web/dashboard/users/index.html.haml, app/views/web/dashboard/users/show.html.haml, config/locales/dashboard/en.yml, config/routes.rb, db/seeds.rb, spec/controllers/web/bootcamp/home_controller_spec.rb, spec/controllers/web/dashboard/users_controller_spec.rb, spec/factories/users.rb, spec/operations/ops/developer/remove_role_spec.rb, spec/policies/user_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/67
Добавил контроллер для пользователей, отображает всех пользователей со статусом active или disabled, можно менять статус.
Создал отдельную страницу с пользователями, где можно удалять или добавлять роль.
Как я понял, еще делается параллельно задача по отправке почты пользователю, пока не разбирался и не добавлял уведомление об изменении статуса пользователя.
=> (#67) add controller Users, change state and roles

Gemfile, Gemfile.lock, app/controllers/web/dashboard/users_controller.rb, app/views/kaminari/_first_page.html.haml, app/views/kaminari/_gap.html.haml, app/views/kaminari/_last_page.html.haml, app/views/kaminari/_next_page.html.haml, app/views/kaminari/_page.html.haml, app/views/kaminari/_paginator.html.haml, app/views/kaminari/_prev_page.html.haml, app/views/web/dashboard/users/index.html.haml, config/initializers/kaminari_config.rb
https://github.com/howtohireme/give-me-poc/issues/92
=> (92) add paginate to Users Management

app/controllers/web/dashboard/test_tasks_controller.rb, app/models/developer/test_task.rb, app/views/web/dashboard/test_task_assignments/show.html.haml, app/views/web/dashboard/test_tasks/edit.html.haml, app/views/web/dashboard/test_tasks/index.html.haml, config/locales/dashboard/en.yml, db/migrate/20180514095047_add_title_to_test_task.rb, db/schema.rb, db/seeds.rb, spec/factories/developer_test_tasks.rb, spec/models/developer/test_task_spec.rb
https://github.com/howtohireme/give-me-poc/issues/61
1. Add 'title' field to TestTask
2. Add display 'title' on page show candidate.
=> (#61) add title field to model test task

app/controllers/web/dashboard/test_tasks_controller.rb, app/models/developer/test_task.rb, app/models/developer/test_task_assignment.rb, app/operations/ops/developer/screening/start.rb, app/views/web/dashboard/test_tasks/edit.html.haml, app/views/web/dashboard/test_tasks/index.html.haml, config/locales/dashboard/en.yml, db/migrate/20180514110648_add_position_to_test_task.rb, db/schema.rb, db/seeds.rb, spec/factories/developer_test_tasks.rb, spec/operations/ops/developer/screening/start_spec.rb
https://github.com/howtohireme/give-me-poc/issues/62
Добавил поле 'position', пробовал менять значения, задачи показываются в зависимости от значения.
=> (#62) add position column to TestTask

app/views/layouts/application.html.haml, app/views/web/bootcamp/registrations/new.html.haml, config/routes.rb
Complete cleanup of RegistrationsController leftovers
=> Remove unexisting routes and related leftovers

CONTRIBUTING.md
=> 95: Added contributing.md

CODE_OF_CONDUCT.md
=> 94: copied code of conduct from juniorjobs

app/views/web/dashboard/users/index.html.haml
=> #147 replace wrong title at dashboard

app/controllers/web/bootcamp/wizard/accept_policies_controller.rb, app/models/developer/wizard.rb, app/models/user.rb, app/operations/ops/developer/accept_policy.rb, app/policies/bootcamp/wizard/accept_policy_policy.rb, app/views/web/bootcamp/wizard/accept_policies/edit.html.haml, config/locales/bootcamp/en.landing.yml, config/routes.rb, spec/controllers/web/bootcamp/oauths_controller_spec.rb, spec/controllers/web/bootcamp/wizard/accept_policies_controller_spec.rb, spec/controllers/web/bootcamp/wizard/profiles_controller_spec.rb, spec/factories/users.rb, spec/models/developer/wizard_spec.rb, spec/models/user_spec.rb, spec/operations/ops/developer/accept_policy_spec.rb, spec/operations/ops/developer/complete_profile_spec.rb, spec/operations/ops/developer/disable_spec.rb, spec/policies/bootcamp/wizard/accept_policy_policy_spec.rb, spec/policies/bootcamp/wizard/profile_policy_spec.rb
#134 Developer must accept policy before editing the profile.
=> Accept policy

app/cells/developer/dashboard/user_status_button.rb, spec/cells/developer/dashboard/user_status_button_spec.rb
https://github.com/howtohireme/give-me-poc/issues/153
Добавил желтый цвет для статуса пользователя pending.
=> (#153) add color yellow to pending status users

app/models/skill.rb, bin/setup, data/skills.yml, db/data/20180605181939_add_skills.rb, db/data_schema.rb, db/migrate/20180604181722_create_skills.rb, db/schema.rb, db/seeds.rb, spec/factories/skills.rb, spec/models/skill_spec.rb
=> 129 introduce skill model

config/initializers/rollbar.rb
https://github.com/howtohireme/give-me-poc/issues/173
add to rollbar ignore tipical attacks
* Step 1
* Step 2
* Step 3
[PR #ID#](https://github.com/howtohireme/give-me-poc-features/pull/#ID#)
=> (#173) add to rollbar ignore tipical attacks

app/cells/developer/dashboard/user_status_button.rb, spec/cells/developer/dashboard/user_status_button_spec.rb
https://github.com/howtohireme/give-me-poc/issues/170
add disabled button to state profile_comleted
* Step 1
* Step 2
* Step 3
[PR #ID#](https://github.com/howtohireme/give-me-poc-features/pull/#ID#)
=> (#170) add disabled button to state profile_comleted

app/models/skill.rb, app/models/user.rb, app/models/user_skill.rb, db/migrate/20180607092448_create_user_skills.rb, db/schema.rb, spec/factories/user_skill.rb, spec/models/role_spec.rb, spec/models/skill_spec.rb, spec/models/user_skill_spec.rb, spec/models/user_spec.rb
https://github.com/howtohireme/give-me-poc/issues/155
Create UserSkill model
* Step 1
* Step 2
* Step 3
[PR #ID#](https://github.com/howtohireme/give-me-poc-features/pull/#ID#)
=> Create UserSkill model

app/controllers/web/bootcamp/wizard/profiles_controller.rb, app/models/user.rb, app/operations/ops/developer/complete_profile.rb, app/views/web/bootcamp/wizard/profiles/edit.html.haml, app/views/web/dashboard/profiles/show.html.haml, app/views/web/dashboard/users/show.html.haml, config/locales/dashboard/en.yml, spec/controllers/web/bootcamp/wizard/profiles_controller_spec.rb, spec/operations/ops/developer/complete_profile_spec.rb, spec/spec_helper.rb
Issue #156 .
Introduce select input, where a user can choose his primary technology.
* Sign in through github
* Complete the profile
* Go to dashboard and inspect your user, it should have primary skill field filled.
[PR 5](https://github.com/howtohireme/give-me-poc-features/pull/5)
=> Select primary skill

app/views/web/dashboard/profiles/edit.html.haml
Issue #ID#.
* Step 1
* Step 2
* Step 3
[PR #ID#](https://github.com/howtohireme/give-me-poc-features/pull/#ID#)
=> Add timezone select to dashboard user profile editing#148

spec/factories/skills.rb, spec/factories/users.rb, spec/queries/users/screening_completed_notification_recipients_query_spec.rb
=> Possible fix of flaky specs

app/services/github_integration/username_resolve_exception.rb, app/services/github_service.rb, db/data/20180616153241_update_users_without_github_username.rb, db/data_schema.rb, spec/services/github_service_spec.rb, spec/spec_helper.rb, spec/support/github_mock.rb
https://github.com/howtohireme/give-me-poc/issues/149
(#149) Creation of migration to fill users field of github username in its absence
* gcm
* gup
* gco 149-fill-missing-github-usernames
* delete github in current user
* rails data:migrate
* check current user github
none
=> (#149) Creation of migration to fill users field of github username

app/operations/ops/developer/invite_to_slack.rb, app/policies/slack_policy.rb, app/services/slack_service.rb, spec/operations/ops/developer/invite_to_slack_spec.rb, spec/policies/slack_policy_spec.rb, spec/services/slack_integration/invite_user_spec.rb, spec/services/slack_service_spec.rb, spec/support/slack_mock.rb
https://github.com/howtohireme/give-me-poc/issues/126
(#126) add list channels for invation to Slack
=> (#126) add list channels for invation to Slack

app/cells/developer/dashboard/user_status_button.rb
https://github.com/howtohireme/give-me-poc/issues/170
(#170) add state policy_accepted to disabled button
=> (#170) add state policy_accepted

app/cells/base_cell.rb, app/cells/developer/dashboard/user_status_button.rb, app/policies/sidekiq_policy.rb, app/views/web/dashboard/users/show.html.haml, lib/sidekiq_constraint.rb, spec/policies/sidekiq_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/135
Ensure that we don't explicitly check user roles
=> (#135) replace has_role? of policy

db/data/20180621203334_update_column_github_users_where_urls.rb, db/data_schema.rb, db/seeds.rb
https://github.com/howtohireme/give-me-poc/issues/124
Migrate existing github urls in the database to new format
* rails db:drop
* bin/setup
* update profile user to url name
* run `rails data:migrate`
* check profile
=> (#124) add data migration update github where urls nickname

app/assets/stylesheets/application.css, app/views/web/bootcamp/wizard/accept_policies/edit.html.haml, config/locales/bootcamp/en.landing.yml
Issue #209 
Slightly update policy page
Just take a look at policy wizard step
none
=> Add link to policy to the corresponding wizard step

LICENSE
https://github.com/howtohireme/give-me-poc/issues/212
add license file
=> (#212) add license file

app/cells/developer/dashboard/user_roles.rb, app/cells/developer/dashboard/user_roles/show.haml, app/policies/user_policy.rb, app/views/web/dashboard/users/show.html.haml, config/locales/dashboard/en.yml, spec/cells/developer/dashboard/user_roles_spec.rb
Issue #181 .
Roles with links for add/delete to cell.
=> User roles to cell

app/views/staff/screening_completed_mailer/notify.html.haml, config/application.rb, config/environments/development.rb, config/environments/features.rb, config/environments/production.rb, config/environments/test.rb
https://github.com/howtohireme/give-me-poc/issues/232
Add a link to applicant to staff new application notification 
* rails c
* user = User.first
* Staff::ScreeningCompletedMailer.notify(user.id).deliver_now
* check the link in the browser window that opens
=> (#232) add in notify to staff link to applicant

app/views/developer/onboarding_started_mailer/notify.html.haml
https://github.com/howtohireme/give-me-poc/issues/233
Update `onboarding started` email template
* rails c
* user = User.first
* Developer::OnboardingStartedMailer.notify(user.id).deliver_now
=> (#233) Update  email template

app/controllers/web/dashboard/test_tasks_controller.rb, app/models/developer/test_task.rb, app/models/role.rb, app/operations/ops/developer/assign_test_tasks.rb, app/views/web/dashboard/test_tasks/_form.html.haml, app/views/web/dashboard/test_tasks/index.html.haml, db/migrate/20180622190740_change_column_test_task_assotiation_to_role.rb, db/schema.rb, spec/controllers/web/dashboard/test_tasks_controller_spec.rb
https://github.com/howtohireme/give-me-poc/issues/231
Change test task association with role through name
* Update Developer::TestTask.first assotiation to role :developer
* check Developer::TestTask.first.role -> "developer"
* Delete role :developer
* Check Developer::TestTask.first.role -> nil
* create role :developer -> User.first.add_role :developer
* Check Developer::TestTask.first.role -> "developer"
https://github.com/howtohireme/give-me-poc-features/pull/11
=> (#231) Change test task association with role through name

app/views/web/dashboard/users/index.html.haml, app/views/web/dashboard/users/show.html.haml
Issue #287 
Fix issue when user haven't completed profile wizard step
=> Fix 500 when the user haven't completed profile step

app/models/note.rb, app/models/user.rb, db/migrate/20180704051906_create_notes.rb, db/schema.rb, spec/factories/notes.rb, spec/models/note_spec.rb, spec/models/user_spec.rb
Issue #225 
Added Note model.
* Step 1
* Step 2
* Step 3
=> Added Note model

app/views/web/dashboard/ideas/_form.html.haml, app/views/web/idea/proposals/_form.html.haml
Issue #302 
Just rename fields
=> Fix wrong fields for Idea forms

.travis.yml
https://github.com/howtohireme/give-me-poc/issues/253
add check seed on travis before install
If seeds failed, then travis build stoping before scripts
=> (#253) add check seed on travis before install

.gitignore, Gemfile, Gemfile.lock, README.md, app/operations/ops/developer/invite_to_github.rb, app/services/github_integration/no_team_found_exception.rb, app/services/github_service.rb, config/initializers/config.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, docs/README.md, docs/github_integration.md, spec/operations/ops/developer/invite_to_github_spec.rb, spec/services/github_service_spec.rb
Issue #286 
* Step 1
* Step 2
* Step 3
=> Add github integration docs

app/helpers/profile_helper.rb, app/views/web/dashboard/profiles/show.html.haml, app/views/web/dashboard/users/show.html.haml, spec/factories/users.rb, spec/helpers/date_helper_spec.rb, spec/helpers/profile_helper_spec.rb
Issue #238 
1. Add github_link helper
2. Change profile of a user
3 Add helper's spec
none
=> add github_link helper, edit profile and add spec

app/models/role.rb, app/queries/users/screening_completed_notification_recipients_query.rb, db/migrate/20180720212240_copy_roles_table.rb, db/schema.rb
Preparing for removing rolify gem from system
Issue #278
=> Rename roles table

app/models/skill.rb, app/models/stack.rb, app/models/stack_skill.rb, app/models/user_skill.rb, data/skills.yml, db/data/20180723180541_add_stack_to_production.rb, db/data_schema.rb, db/migrate/20180723172036_create_stacks.rb, db/migrate/20180723173209_create_stack_skills.rb, db/schema.rb, db/seeds.rb, spec/factories/stack_skills.rb, spec/factories/stacks.rb, spec/models/stack_skill_spec.rb, spec/models/stack_spec.rb
https://github.com/howtohireme/give-me-poc/issues/196
(#196) add stack model and data migration
* rails db:schema:load
* rails db:seed
* rails c
* Stack.all
* Stack.first.skills
* Skill.first.stacks
=> (#196) add stack model and data migration

app/helpers/application_helper.rb, app/models/user.rb, app/views/layouts/dashboard.html.haml, spec/helpers/application_helper_spec.rb
Issue #335 
1. Add a scope for pending users in model
2. Add the counter in view
* Step 1
* Step 2
* Step 3
=> add count of pending users

app/policies/dashboard/idea_policy.rb, spec/policies/web/dashboard/idea_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/297
ban rejection if the current user is the author of the idea
* Create new idea
* Show idea
* Button 'reject' hide
https://monosnap.com/file/I6KUDHkGMSBR3ROvFE5uaxJyoOdXaT
=> (#297) ban rejection if the current user is the author of the idea

app/views/web/dashboard/ideas/index.html.haml
https://github.com/howtohireme/give-me-poc/issues/298
(#298) delete description idea on index page
* go to http://dashboard.lvh.me:3000/ideas
* 3 columns are presented: Name, Status, Author
https://monosnap.com/file/SEIrRkOEXSIalcpFsKK2C0rgUzNIg3
=> (#298) delete description idea on index page

app/models/project.rb, app/models/project_user.rb, app/models/stack.rb, app/models/user.rb, app/operations/ops/idea/upvote.rb, app/operations/ops/projects/kickoff.rb, db/migrate/20180731101834_create_project_users.rb, db/migrate/20180731103201_add_references_project_to_stack.rb, db/schema.rb, spec/factories/project_users.rb, spec/factories/projects.rb, spec/factories/stacks.rb, spec/factories/votes.rb, spec/models/project_spec.rb, spec/models/project_user_spec.rb, spec/models/user_spec.rb, spec/operations/ops/projects/kickoff_spec.rb
https://github.com/howtohireme/give-me-poc/issues/11
(#11) add create project when 5 votes up idea
* Create new Idea and change status to voting
* Add vote up to idea
* go to rails c
* idea = Idea.last
* Ops::Projects::Kickoff.call(idea: idea)
* Check:
* idea = Idea.last
* idea.state
* idea.project
* idea.project.users
=> (#11) add create project when 5 votes up idea

app/cells/web/dashboard/user_notes.rb, app/cells/web/dashboard/user_notes/show.haml, app/controllers/web/dashboard/base_controller.rb, app/controllers/web/dashboard/ideas_controller.rb, app/controllers/web/dashboard/notes_controller.rb, app/controllers/web/dashboard/skills_controller.rb, app/controllers/web/dashboard/test_task_assignments_controller.rb, app/controllers/web/dashboard/test_tasks_controller.rb, app/controllers/web/dashboard/users_controller.rb, app/policies/dashboard/note_policy.rb, app/policies/dashboard_policy.rb, app/views/notes/new.html.haml, app/views/web/dashboard/users/show.html.haml, config/locales/dashboard/en.yml, config/locales/en.yml, config/routes.rb, spec/cells/web/dashboard/user_notes_spec.rb, spec/controllers/web/dashboard/notes_controller_spec.rb, spec/controllers/web/dashboard/skills_controller_spec.rb, spec/policies/web/dashboard/note_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/226
(#226) add notes to users
* Go to example: http://dashboard.lvh.me:3000/users/10
* Click Notes create button
* Create note to user
* Check notes on user page
=> (#226) add notes to users

app/controllers/web/dashboard/ideas_controller.rb, app/controllers/web/dashboard/projects_controller.rb, app/controllers/web/dashboard/skills_controller.rb, app/controllers/web/dashboard/users_controller.rb, app/models/project.rb, app/policies/dashboard/idea_policy.rb, app/policies/dashboard/project_policy.rb, app/policies/dashboard_policy.rb, app/queries/projects/projects_author_idea_query.rb, app/views/layouts/dashboard.html.haml, app/views/web/dashboard/ideas/index.html.haml, app/views/web/dashboard/projects/edit.html.haml, app/views/web/dashboard/projects/index.html.haml, app/views/web/dashboard/projects/show.html.haml, app/views/web/dashboard/users/show.html.haml, config/locales/dashboard/en.yml, config/routes.rb, db/migrate/20180803192102_change_index_slug_on_projects.rb, db/schema.rb, spec/controllers/web/dashboard/projects_controller_spec.rb, spec/controllers/web/dashboard/votes_controller_spec.rb, spec/factories/ideas.rb, spec/factories/projects.rb, spec/factories/stacks.rb, spec/operations/ops/idea/upvote_spec.rb, spec/policies/web/dashboard/idea_policy_spec.rb, spec/policies/web/dashboard/project_policy_spec.rb, spec/queries/projects/projects_author_idea_query_spec.rb, spec/queries/reviewable_applicants_query_spec.rb
https://github.com/howtohireme/give-me-poc/issues/202
(#202) add manage projects
go to http://dashboard.lvh.me:3000/projects
=> (#202) add manage projects

app/models/role.rb, app/models/roles/author.rb, app/models/roles/developer.rb, app/models/roles/mentor.rb, app/models/roles/roles_manager.rb, app/models/roles/staff.rb, db/data/20180729113529_migrate_roles_state.rb, db/data_schema.rb, db/migrate/20180729111441_add_state_column_to_role.rb, db/schema.rb, spec/models/roles/roles_manager_spec.rb
Issue #279
[PART-2](https://github.com/howtohireme/give-me-poc/pull/342)
This PR moves the state machine from User to Roles::SomeRole, and fills the new state machines with current states from User.
Just ensure that we don't have any regressions
=> [PART-1] 279 Roles refactoring

app/controllers/web/dashboard/ideas_controller.rb, app/controllers/web/dashboard/votes_controller.rb, app/operations/ops/idea/activate.rb, app/operations/ops/idea/upvote.rb, app/operations/ops/projects/kickoff.rb, config/locales/dashboard/en.yml, spec/controllers/web/dashboard/ideas_controller_spec.rb, spec/controllers/web/dashboard/votes_controller_spec.rb, spec/operations/ops/idea/activate_spec.rb, spec/operations/ops/idea/upvote_spec.rb, spec/operations/ops/projects/kickoff_spec.rb
https://github.com/howtohireme/give-me-poc/issues/359
https://github.com/howtohireme/give-me-poc/issues/360
Now, when the idea is activated, the project is created
=> (#359) create project when activate idea

app/models/concerns/rolable.rb
https://github.com/howtohireme/give-me-poc/issues/369
(#369) add sort to roles name
* Step 1
* Step 2
* Step 3
=> (#369) add sort to roles name

app/views/mailers/developer/disabled_notification_mailer/notify.html.haml, app/views/mailers/developer/onboarding_started_mailer/notify.html.haml, app/views/mailers/developer/rejection_notification_mailer/notify.html.haml, app/views/mailers/layouts/mailer.html.haml, app/views/mailers/staff/screening_completed_mailer/notify.html.haml, config/locales/dashboard/en.yml
Issue #ID
* Step 1
* Step 2
* Step 3
https://monosnap.com/file/Ltes8dpMe94dNLL7CRY5nwPdJPfVbQ
https://monosnap.com/file/SU51z21EIDvZLkL8FeBvoTAzxJQMW2
https://monosnap.com/file/KZkaGtgnXRkkaYXmUKb8xvZHXAsGA9
=> refactoring mailers templates

app/operations/ops/projects/generate_project_github_team.rb, app/services/github_service.rb, spec/factories/ideas.rb, spec/operations/ops/projects/generate_project_github_team_spec.rb, spec/services/github_service_spec.rb
#198
(#198) github repo generation
* Step 1
* Step 2
* Step 3
=> (#198) github repo generation

app/cells/developer/dashboard/user_status_button.rb, app/controllers/web/dashboard/role_activation_controller.rb, app/controllers/web/dashboard/role_deactivation_controller.rb, app/models/role.rb, app/operations/ops/developer/base_operation.rb, app/operations/ops/roles/activate.rb, app/operations/ops/roles/deactivate.rb, app/policies/dashboard/role_change_state_policy.rb, config/locales/dashboard/en.yml, config/routes.rb, spec/cells/developer/dashboard/user_status_button_spec.rb, spec/controllers/web/dashboard/role_activation_controller_spec.rb, spec/controllers/web/dashboard/role_deactivation_controller_spec.rb, spec/models/role_spec.rb, spec/operations/ops/roles/activate_spec.rb, spec/operations/ops/roles/deactivate_spec.rb, spec/policies/web/dashboard/note_policy_spec.rb, spec/policies/web/dashboard/role_change_state_policy_spec.rb
https://github.com/howtohireme/give-me-poc/issues/384
(#384) add change state to roles
* Step 1
* Step 2
* Step 3
=> (#384) add change state to roles

app/cells/web/dashboard/user_notes/show.haml, app/controllers/web/dashboard/notes_controller.rb, app/models/concerns/rolable.rb, app/policies/dashboard/note_policy.rb, app/policies/dashboard_policy.rb, app/views/notes/_form.html.haml, app/views/notes/edit.html.haml, app/views/notes/new.html.haml, app/views/web/dashboard/users/show.html.haml, config/locales/en.yml, config/routes.rb, spec/controllers/web/dashboard/notes_controller_spec.rb, spec/policies/test_task_assignment_policy_spec.rb, spec/policies/test_task_policy_spec.rb, spec/policies/web/dashboard/note_policy_spec.rb, spec/policies/web/dashboard/project_policy_spec.rb, spec/policies/web/dashboard/role_change_state_policy_spec.rb, spec/policies/web/dashboard/skill_policy_spec.rb
fix policy and specs, refactoring notes and add manage user notes
Staff and mentor can edit their notes and delete all notes
https://monosnap.com/file/v9dKDZk700r0R2iL8IHzRtwD0kXAvx
=> fix policy and specs, refactoring notes and add manage user notes

app/views/layouts/application.html.haml, app/views/layouts/bootcamp.html.haml, app/views/layouts/idea.html.haml, app/views/layouts/shared/_navigation.html.haml
Issue #276 
Add ideas link to all menus
=> Unify landings navigation

.travis.yml, bin/load_dump, bin/make-db-backup, bin/test-migrations, config/database.yml.sample, config/database.yml.travis
Issue #332 
Refactor db backup scripts
check if the build is green
[PR 26](https://github.com/howtohireme/give-me-poc-features/pull/26)
=> 332 improve backup scripts

bin/rebase
Issue #190 
Add `bin/rebase` script
=> Added bin/rebase script

app/views/layouts/application.html.haml, app/views/layouts/bootcamp.html.haml, app/views/layouts/dashboard.html.haml, app/views/layouts/idea.html.haml, app/views/layouts/shared/_analytics.html.haml
Issue #ID
* Step 1
* Step 2
* Step 3
=> Add google analytics

.travis.yml, bin/build, bin/deploy, bin/travis-features
Issue #ID
* Step 1
* Step 2
* Step 3
=> 128 travis stages

app/jobs/screening/send_followup_job.rb, spec/jobs/screening/send_followup_job_spec.rb
=> Call operation in SendFollowupJob

app/views/web/idea/home/index.html.haml, config/locales/idea/en.yml
Issue #441 
Improve texts on ideas landing
[PR 30](https://github.com/howtohireme/give-me-poc-features/pull/30)
=> Improve idea landing text

app/queries/users/screening_completed_notification_recipients_query.rb, spec/queries/users/screening_completed_notification_recipients_query_spec.rb
https://github.com/howtohireme/give-me-poc/issues/462
462 fix repeat emails
* Step 1
* Step 2
* Step 3
before:
https://monosnap.com/file/T8Afl0ArOCNy4ONPrBeKtOxQKMrLgC
after:
https://monosnap.com/file/M7bDhvDeut0aLdBkP86ulZXsJ5CiVp
=> 462 fix repeat emails

app/assets/stylesheets/overrides.scss, app/views/web/home/index.html.haml, app/views/web/shared/_newsletter.html.haml, config/locales/en.yml, config/locales/ru.yml
Issue #358 
Adding form to the root landing that allows subscribing to our newsletter.
=> Add mailchimp newletter form to the root landing

README.md
Issue #515 
add badge
[PR #517 ](https://github.com/howtohireme/give-me-poc-features/pull/515)
=> add CodeTriage badge

Dockerfile, Gemfile, Gemfile.lock
Issue has no ID
Fix security problems described [here](https://github.com/howtohireme/give-me-poc/network/alert/Gemfile.lock/loofah/open)
Check version in `Gemfile.lock`
https://github.com/howtohireme/give-me-poc/network/alert/Gemfile.lock/loofah/open
No special steps for checking this feature
Renamed branch as required in [PR](https://github.com/howtohireme/give-me-poc/pull/518)
=> Urgent update security

app/views/layouts/shared/_footer.html.haml
=> Updated year on views/shared/_footer.html.haml

app/views/web/dashboard/ideas/index.html.haml, config/locales/dashboard/en.yml, config/locales/dashboard/ru.yml
=> #528: Added date to idea list

app/helpers/nav_bar_menu_helper.rb, app/views/layouts/dashboard.html.haml, config/locales/dashboard/en.yml, config/locales/dashboard/ru.yml, spec/helpers/nav_bar_menu_helper_spec.rb
Issue #ID
#500 
Different states of the application with applicants :screening_complete and ideas with :pending state
https://monosnap.com/file/HYcwpakXTJjuUJr0cVZRQHXAuF6AgB
https://monosnap.com/file/IJn5oAz7dWxDzZvhsCvIJmi57bh43t
https://monosnap.com/file/gcKbxm6hHD4lVInrIxS9tTeHrszm60
=> Added counter of pending ideas into Dashboard
